# -*- coding: utf-8 -*-
"""store.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mhCOIuZGxFFw0iQzCBdB7Gl-ucydnIPe

Создание файла
"""

import csv

with open("store.csv", mode="w", encoding='utf-8') as w_file:
    file_writer = csv.writer(w_file, delimiter = ",", lineterminator="\r")
    file_writer.writerow(["Название", "Количество", "Производитель", "Цена", "Размер"])
    active = True
    while active:      
      file_writer.writerow([input('Введите название товара: '), 
                            int(input('Введите количество: ')),
                            input('Введите производителя: '),
                            float(input('Введите цену: ')),
                            input('Введите размер: ')
                            ])
      repeat = input("Желаете продолжить опрос? (yes/no) ")
      if repeat == 'no':
        active = False
print("Товары добавлены")

"""Добавление новых элементов"""

with open("store.csv", mode="a", encoding='utf-8') as w_file:
    file_writer = csv.writer(w_file, delimiter = ",", lineterminator="\r")    
    active = True
    while active:      
      file_writer.writerow([input('Введите название товара: '), 
                            int(input('Введите количество: ')),
                            input('Введите производителя: '),
                            float(input('Введите цену: ')),
                            input('Введите размер: ')
                            ])
      repeat = input("Желаете продолжить опрос? (yes/no) ")
      if repeat == 'no':
        active = False
print("Товары добавлены")

with open("store.csv", encoding='utf-8') as r_file:
    # Создаем объект DictReader, указываем символ-разделитель ","
    file_reader = csv.DictReader(r_file, delimiter = ",")
    # Счетчик для подсчета количества строк и вывода заголовков столбцов
    count = 0
    # Считывание данных из CSV файла
    for row in file_reader:
        if count == 0:
            # Вывод строки, содержащей заголовки для столбцов
            print(f'Файл содержит столбцы: {", ".join(row)}')
        # Вывод строк
        print(f' Название: {row["Название"]}, Размер: {row["Размер"]}, Производитель: {row["Производитель"]}', end='\n')
        count += 1
    print(f'Всего в файле {count + 1} строк.')

"""удаление элементов

"""

with open('store.csv') as infile:
    reader = csv.reader(infile)
    header = next(reader)
    data = list(reader)
    
new_data = [row for row in data if row[0].find("nike")] # Remove unwanted rows

with open('filename.csv', 'w') as outfile:
    writer = csv.writer(outfile)
    writer.writerow(header)
    writer.writerows(new_data)

new_data